version: '3'

networks:
  nuxt-network:
    driver: bridge
  default:


volumes:
  public-storage:
  node_modules: {}

services:
  aue_frontend:
    build:
      dockerfile: ../docker/nuxt/Dockerfile
      context: './../frontend'
      args:
        - BASE_URL=https://3220911-ew88386.twc1.net
        - API_URL=https://3220911-ew88386.twc1.net/api
        - BACK_URL=https://3220911-ew88386.twc1.net
    image: nginx:latest
    environment:
      - HOST=0.0.0.0
      - PORT=80
    restart: "no"
    ports:
      - "24680:24678"
      - "5000:80"
      - "445:443"
    volumes: 
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - nuxt-network
      - default
